### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by cloudgrayau** [putyourlightson/craft-spark#13]
### Support Request

Hello,

I am just looking at possibly replacing Sprig with Spark on a website I am developing. I know that most of these will rely on the actual Datastar framework, but I can't find any documentation on either of them on the Datastar docs.

1) Is there a JavaScript afterSwap 'event' equivalent, similar to:
- htmx.on('htmx:afterSwap', function(){});

2) I also have some custom AJAX running. Is there any option to run the returned HTML through Spark? Similar to the HTMX equivalent:
- htmx.process();

Thanks,

**Comment by bencroker** [comment]
1. No, but there is `data-on-load`, which is triggered whenever the element is loaded into the DOM. You can use this if you need to trigger some JS after an element has been swapped in. See the docs on using [external scripts](https://putyourlightson.com/plugins/spark#external-scripts).
```twig
<div data-on-load="myfunction()"></div>
```

2. Is there any reason you can’t fetch the content via Spark? This might work, but it’s generally advised to avoid such trickery when at all possible.
```js
ds.applyPlugins(element)
```

**Comment by cloudgrayau** [comment]
Yep, perfect. Thanks.

It appears with point 2, that the AJAX fetched content already triggers spark, which was my mistake.
