### ISSUE TITLE
How to pass array values to the store (checkboxes / multi-select)

### ISSUE THREAD

**Issue by croxton** [putyourlightson/craft-spark#6]
### Support Request

Sorry if I've missed something basic, but I'm trying to use either a `<select multiple>`  or a group of checkboxes to pass an array of values for a variable `colours`:

```twig
<section data-store="{ colours:[] }">
  Colours:
  {% for option in colours %}
      <label for="colours-{{ option.id }}">
          <input id="colours-{{ option.id }}"
              type="checkbox"
              value="{{ option.id }}"
              data-model="colours"
              data-on-click="$$get('{{ sparkUrl('_shared/spark/search-results.twig' }}')"
              name="colours[]"
          >
          <span>{{ option.title }}</span>
      </label>
  {% endfor %}
</section>
```

This only ever passes the value of the selected checkbox, rather than an array of values for all checkboxes that share the same `data-model="colours"` - and then when it renders the result all checkboxes are selected.

Unfortunately there are no multi-select type form controls listed here:
https://data-star.dev/examples/model_binding

**Comment by bencroker** [comment]
I'm not sure how you'd handle this, maybe @delaneyj knows?

**Comment by delaneyj** [comment]
I tend not to do multi-select so it may not work with the current plugins.  I'll try to find time to spin an example up and fix anything preventing it.

**Comment by delaneyj** [comment]
v0.19.5 has support!

**Comment by bencroker** [comment]
Thanks, @delaneyj!

Here is the [example](https://data-star.dev/examples/multi_select).
