### ISSUE TITLE
Syntax broken in `0.0.7`?

### ISSUE THREAD

**Issue by wbrowar** [putyourlightson/craft-spark#7]
### Bug Report

Hey @bencroker, I updated Spark to `0.0.7`, updated my example code and tried to run it and got the following error in Chrome:

<img width="1519" alt="Screenshot 2024-10-20 at 2 31 30 PM" src="https://github.com/user-attachments/assets/8b58dd81-790b-486d-b320-ba1e80908f2f">

Here is the demo code I'm using. This is in my `index.twig` file:

```twig
{# Basic store and POST request test. #}
<div data-store="{ textInput: 'planet' }">
    <input type="text" placeholder="Type here!" data-model="textInput" data-on-blur="{{ spark('_spark/main.twig', {}, 'post') }}')" />

    <button id="main-button" data-on-click="{{ spark('_spark/main.twig', {}, 'post') }}')">
        Change it!
    </button>

    <div id="first">
        This is the first thing.
    </div>

    <div id="second">
        This is the second thing.
    </div>
</div>
```

And this is in my `main.twig` file:
```twig
{# templates/_spark/main.twig #}

<div id="first">
  Oh, hi, {{ store.textInput }}!
</div>

<div id="second">
  And uh, hello, {{ currentUser.friendlyName ?? 'nobody' }}?
</div>
```

To isolate this I commented out the rest of the things I was testing Spark for so this should be the only thing interacting with Spark.

---

Also, unrelated to my issue above, I noticed a few typos in [the docs](https://putyourlightson.com/plugins/spark):

- A few instances where `'post'` is missing a trailing single quote: `{{ spark('_spark/save-entry.twig', [], 'post) }}`
- Where `method: 'post'` isn't in an object (I don't know if this is an issue but I think so): `{{ spark('_spark/save-entry.twig', method: 'post) }}`
- Should an empty set of arguments be `{}` in Twig, instead of `[]`: `{{ spark('_spark/save-entry.twig', [], 'post) }}`

### Plugin Version

0.0.7

### Craft CMS Version

5.4.8

### PHP Version

8.2.22

**Comment by bencroker** [comment]
You have an extra trailing `')`.

```twig
data-on-blur="{{ spark('_spark/main.twig', {}, 'post') }}')"
```

It should read:

```twig
data-on-blur="{{ spark('_spark/main.twig', {}, 'post') }}"
```

**Comment by bencroker** [comment]
None of those appear to be typos in the docs, but let me know if I’ve overlooked something. I did a lot of work on the docs today and some clean up will likely follow.

**Comment by wbrowar** [comment]
Ah, good eye on the extra `')`. I took them all out and it's all working correctly again!

Regarding the docs, I'm still seeing some of the things I mentioned above, so maybe it's a rendering issue with the doc blocks?

<img width="822" alt="Screenshot 2024-10-20 at 6 27 28 PM" src="https://github.com/user-attachments/assets/7c46165d-5981-443f-8f47-cc46bf3391f7">

**Comment by bencroker** [comment]
Fixed the missing trailing single quote, thanks! In this case, `method: 'post'` is a named argument, and not meant to be an object. 

> If you prefer, you can also use a named argument for the method, which may be desirable when not passing variables into the template.
