### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by svondervoort** [putyourlightson/craft-spark#9]
### Bug Report

The example code is missing a `'` after the `'post` portion of the `{{ spark }}` include on line `#22`.

``` 
<button data-on-click="{{ spark('_spark/save-entry.twig', {}, 'post) }}" data-show="$entryId == {{ entry.id }}">
```

Should be

``` 
<button data-on-click="{{ spark('_spark/save-entry.twig', {}, 'post') }}" data-show="$entryId == {{ entry.id }}">
```

Also on line `#18` ` id="edit-{{ entry.id }}"` is missing from the edit button which gives a console error from Datastar with target not found.

### Plugin Version

n/a

### Craft CMS Version

n/a

**Comment by bencroker** [comment]
Thanks for reporting that, should be all fixed now.
